Repository Zukdoor/ZukBoard, pull requests merged in 2018-10, with the labels that each got.

#92 refact: move img to CDN
  src/api/server/oss.js
  src/api/server/router.js
  src/app/client/pages/canvas/draw/draw.js
  src/app/client/pages/canvas/draw/plugins/upload-img/action.vue
  src/app/client/pages/canvas/draw/plugins/util.js
Labels: review

#96 Move to Heroku
  .travis.yml
  app.js
  config.js
  ecosystem.config.js
  id_rsa.enc
  package.json
  public/dist/js/manifest.6499b486fe8e5e729f4d.js
  public/dist/js/manifest.6499b486fe8e5e729f4d.js.map
  src/api/server/router.js
  src/app/client/pages/canvas/draw/components/board.vue
  src/app/client/pages/canvas/draw/plugins/brush/plugin.js
  src/app/client/pages/canvas/draw/plugins/upload-img/plugin.js
  yarn.lock
Labels: review

#104 fixed #91
  src/app/client/pages/canvas/draw/draw.js
  src/app/client/pages/canvas/draw/plugins/util.js
Labels: review

#106 fixed #105
  server/socket.js
  src/app/client/pages/canvas/draw/components/board.vue
Labels: review

#110 fix: https can't upload image
  src/api/server/oss.js
Labels: review

#115 Docker deploy on Now
  .travis.yml
  Dockerfile
  config.js
  deploy-staging.sh
  deploy.sh
  ecosystem.config.js
  entrypoint.sh
  package.json
  src/app/client/main.js
  yarn.lock
Labels: enhancement, review

#116 fixed highlight color on ios default
  src/app/client/pages/canvas/draw/components/board.vue
Labels: review

#117 fix: should remove borders after removing multi elements(#113)
  src/app/client/pages/canvas/draw/draw.js
Labels: review

#120 Fix GA
  build/webpack.base.conf.js
  deploy-staging.sh
  deploy.sh
  public/favicon.ico
  src/app/client/main.js
  src/app/client/router/index.js
Labels: bug, review

#121 fixed #118 and #119
  src/app/client/App.vue
  src/app/client/pages/canvas/draw/plugins/brush/setting.vue
  src/app/client/pages/canvas/draw/plugins/setting.js
Labels: review

#129 merge Develop
  .travis.yml
  public/dist/js/manifest.6499b486fe8e5e729f4d.js
  public/dist/js/manifest.6499b486fe8e5e729f4d.js.map
Labels: review

#131 feat: add sync mode
  server/socket.js
  src/app/client/assets/icon.css
  src/app/client/pages/canvas/draw/components/SyncStatusNotify.vue
  src/app/client/pages/canvas/draw/components/board.vue
  src/app/client/pages/canvas/draw/draw.js
  src/app/client/pages/canvas/draw/plugins/setting.js
Labels: review

#134 Before upload compress image and add getsture enlarge canvas on pad
  src/app/client/pages/canvas/draw/draw.js
  src/app/client/pages/canvas/draw/plugins/fabricOverriding.js
  src/app/client/pages/canvas/draw/plugins/setting.js
  src/app/client/pages/canvas/draw/plugins/upload-img/action.vue
  src/app/client/pages/canvas/draw/plugins/upload-img/handleImage.js
  src/app/client/pages/canvas/draw/plugins/util.js
Labels: review

#138 Enter space key can drag canvas and when enter shiftkey select some object then click blank area selected object unselect
  src/app/client/pages/canvas/draw/draw.js
  src/app/client/pages/canvas/draw/plugins/fabricOverriding.js
Labels: review

#139 fixed when ios 10.2 safari broswer can not upload image
  src/app/client/pages/canvas/draw/plugins/util.js
Labels: review

#144 Add feature
  Dockerfile
  src/api/server/oss.js
  src/app/client/pages/canvas/draw/components/board.vue
  src/app/client/pages/canvas/draw/draw.js
  src/app/client/pages/canvas/draw/plugins/events.js
  src/app/client/pages/canvas/draw/plugins/fabricOverriding.js
  src/app/client/pages/canvas/draw/plugins/setting.js
Labels: review

#153 fixed bug
  src/app/client/pages/canvas/draw/components/board.vue
  src/app/client/pages/canvas/draw/draw.js
  src/app/client/pages/canvas/draw/plugins/events.js
  src/app/client/pages/canvas/draw/plugins/fabricOverriding.js
Labels: review

#152 fix: synchronization of multi-element operations
  db/mongo.js
  package.json
  server/socket.js
  server/socket/constant.js
  server/socket/index.js
  server/socket/methods.js
  server/socket/registerFollow.js
  server/socket/registerSync.js
  src/api/server/router.js
  src/app/client/pages/canvas/draw/components/board.vue
  src/app/client/pages/canvas/draw/draw.js
  src/app/client/pages/canvas/draw/plugins/setting.js
Labels: review

#158 fix: redo/undo sync bug
  server/socket/registerSync.js
  src/app/client/pages/canvas/draw/components/board.vue
  src/app/client/pages/canvas/draw/draw.js
Labels: review

#165 fixed can not select objects
  src/app/client/pages/canvas/draw/draw.js
Labels: review

#169 fix #168
  src/app/client/pages/canvas/draw/components/board.vue
  src/app/client/pages/canvas/draw/draw.js
Labels: review
